const productList = [
    {
      id: 1,
      titulo: 'Tv Noblex 32" Dk 32x5000 Smart',
      descripcion: 'Tv de 32" Smart LED HD (1366x768). Frecuencia de barrido 60Hz. Radio contraste 3000:1. Brillo 180 CD/M2. Potencia 6W RMS (x2). Wi Fi. Sintonizador TDA. 2 USB. 2 HDMI. Contraste dinamico 3000:1. Sonido Estereo.',
      precio: 59599,
      desc: '46% OFF',
      condicion1: 'Contado',
      condicion2: 'Debito',
      condicion3: '1 Pago',
      precio2: 39599,
      stock: 5,
      categoria: 'tv',
      image: '/images/products/tvNoblex.avif',
    },
    {
        id: 2,
        titulo: 'Celular Motorola G60S 6.7" 128GB',
        descripcion: 'Fotografía profesional en tu bolsillo, descubrí infinitas posibilidades para tus fotos con las 4 cámaras principales de tu equipo. Poné a prueba tu creatividad y jugá con la iluminación, diferentes planos y efectos para obtener grandes resultados.',
        precio: 109099,
        desc: '44% OFF',
        condicion1: 'Contado',
        condicion2: 'Debito',
        condicion3: '1 Pago',
        precio2: 60099,
        stock: 3,
        categoria: 'celular',
        image: '/images/products/celularMotorola.avif',
    },
    {
        id: 3,
        titulo: 'Aire Split Bgh 6300W',
        descripcion: 'Split frio calor de 6300W (5800 frog.). Display con opcion activado u oculto. Deshumidificacion y filtro antipolvo. Gas R410A. Clase energetica A.',
        precio: 248399,
        desc: '39% OFF',
        condicion1: 'Contado',
        condicion2: 'Debito',
        condicion3: '1 Pago',
        precio2: 149099,
        stock: 4,
        categoria: 'airesplit',
        image: '/images/products/aireBgh.avif',
    },
    {
      id: 4,
      titulo: 'Tv Led BGH 32" Smart HD NTF',
      descripcion: 'Este Smart TV de BGH viene con Wi-Fi incorporado para que puedas acceder a internet de forma inalámbrica. Disfrutá de tus app preferidas como Netflix y YouTube, entre otras.',
      precio: 54099,
      desc: '39% OFF',
      condicion1: 'Contado',
      condicion2: 'Debito',
      condicion3: '1 Pago',
      precio2: 32499,
      stock: 2,
      categoria: 'tv',
      image: '/images/products/tvledBgh.avif',
    },
    {
      id: 5,
      titulo: 'Celular Motorola EDGE20 Lite 6.7" 6gb 128gb Gris',
      descripcion: 'Descubrí infinitas posibilidades para tus fotos con las 3 cámaras principales de tu equipo. Poné a prueba tu creatividad y jugá con la iluminación, diferentes planos y efectos para obtener grandes resultados.',
      precio: 121099,
      desc: '44% OFF',
      condicion1: 'Contado',
      condicion2: 'Debito',
      condicion3: '1 Pago',
      precio2: 66699,
      stock: 6,
      categoria: 'celular',
      image: '/images/products/celularMotorolaEdge20.avif',
    },
  ]

  export default productList;